### ISSUE TITLE
istanbul does not work in babel plugins

### ISSUE THREAD

**Issue by EricTiger** [istanbuljs/babel-plugin-istanbul#206]
After I reinstall node_modules using old package.json (no update manually, only npm install ), there is a new error thrown from babel when running webpack. If I use old node_modules, the error does not occur.

Module build failed: Error:xxx/xxx/xxx.ts: You gave us a visitor for the node type "ClassPrivateProperty" but it's not a valid type
    at verify (/Users/eric/Workspace/dev/xxx/node_modules/babel-traverse/lib/visitors.js:196:13)
    at Object.explode (/Users/eric/Workspace/dev/xxx/node_modules/babel-traverse/lib/visitors.js:72:3)
    at traverse (/Users/eric/Workspace/dev/xxx/node_modules/babel-traverse/lib/index.js:77:12)
    at NodePath.traverse (/Users/eric/Workspace/dev/xxx/node_modules/babel-traverse/lib/path/index.js:144:25)
    at Object.enter (/Users/eric/Workspace/dev/xxx/node_modules/istanbul-lib-instrument/dist/visitor.js:611:12)
    at PluginPass.enter (/Users/eric/Workspace/dev/xxx/node_modules/babel-plugin-istanbul/lib/index.js:90:23)
    at newFn (/Users/eric/Workspace/dev/xxx/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/eric/Workspace/dev/xxx/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/eric/Workspace/dev/xxx/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/eric/Workspace/dev/xxx/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/eric/Workspace/dev/xxx/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/eric/Workspace/dev/xxx/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/eric/Workspace/dev/xxx/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/eric/Workspace/dev/xxx/node_modules/babel-traverse/lib/index.js:114:17)
    at traverse (/Users/eric/Workspace/dev/xxx/node_modules/babel-traverse/lib/index.js:79:12)
    at File.transform (/Users/eric/Workspace/dev/xxx/node_modules/babel-core/lib/transformation/file/index.js:516:35)

My old package.json is
`
"dependencies": {
    "@types/core-js": "^0.9.43",
    "@types/google-libphonenumber": "^7.4.15",
    "@types/qs": "^6.5.1",
    "@types/socket.io-client": "^1.4.31",
    "axios": "^0.15.3",
    "core-js": "^2.5.3",
    "google-libphonenumber": "^3.0.9",
    "jsonschema": "^1.2.0",
    "moment": "^2.19.3",
    "qs": "^6.5.1",
    "raven-js": "^3.21.0",
    "rx-dom": "^7.0.3",
    "rxjs": "^5.5.2",
    "rxjs-spy": "^6.0.0",
    "socket.io-client": "^2.0.4",
    "vue": "2.5.13",
    "vue-block": "^1.0.8",
    "vue-class-component": "^6.1.0",
    "vue-i18n": "^7.4.0",
    "vue-property-decorator": "^6.0.0",
    "vue-router": "^3.0.1",
    "vue-rx": "^5.0.0",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@fimbul/valtyr": "^0.3.0",
    "@fimbul/ve": "^0.2.0",
    "@fimbul/wotan": "^0.3.0",
    "@types/mocha": "~2.2.42",
    "@types/node": "~8.0.24",
    "@types/sinon": "~2.3.3",
    "autoprefixer": "^7.1.2",
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.5",
    "babel-plugin-istanbul": "^5.1.0",
    "babel-preset-env": "^1.7.0",
    "chai": "^4.1.2",
    "chalk": "^2.0.1",
    "commitlint": "^6.1.3",
    "connect-history-api-fallback": "^1.3.0",
    "copy-webpack-plugin": "^4.0.1",
    "cross-env": "^5.0.1",
    "cross-spawn": "^5.0.1",
    "css-loader": "^0.28.0",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.14.1",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^1.1.4",
    "fork-ts-checker-webpack-plugin": "^0.4.1",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "html-webpack-plugin": "^2.30.1",
    "http-proxy-middleware": "^0.17.3",
    "inject-loader": "^3.0.0",
    "karma": "^3.1.4",
    "karma-coverage": "^1.1.2",
    "karma-mocha": "^1.3.0",
    "karma-puppeteer-launcher": "^1.0.2",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-spec-reporter": "0.0.32",
    "karma-webpack": "^3.0.5",
    "less": "^2.7.2",
    "less-loader": "^3.0.0",
    "lint-staged": "^6.1.0",
    "loader-utils": "^1.1.0",
    "mocha": "^5.2.0",
    "mockjs": "^1.0.1-beta3",
    "mustache": "^2.3.0",
    "opn": "^5.1.0",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "ora": "^1.2.0",
    "portfinder": "^1.0.13",
    "puppeteer": "^1.11.0",
    "request": "^2.85.0",
    "rimraf": "^2.6.0",
    "selenium-server": "^3.0.1",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "sinon": "^4.0.0",
    "sinon-chai": "^2.8.0",
    "socket.io": "^2.0.4",
    "svg-sprite-loader": "^0.3.1",
    "ts-loader": "^2.0.3",
    "tslint": "~5.6.0",
    "tslint-eslint-rules": "^5.1.0",
    "tslint-loader": "~3.5.3",
    "typescript": "~2.4.2",
    "url-loader": "^0.5.8",
    "vue-loader": "^14.2.1",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "2.5.13",
    "webpack": "^3.6.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-middleware": "^1.12.0",
    "webpack-hot-middleware": "^2.18.2",
    "webpack-merge": "^4.1.0",
    "zip-webpack-plugin": "^2.1.0"
  },
  "engines": {
    "node": ">= 4.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
`

.babelrc is
`
{
    "presets": ["babel-preset-env"],
    "plugins": ["istanbul"]  // if no this plugin, no error occurs
}
`

**Comment by coreyfarrell** [comment]
babel-plugin-istanbul@5 does not support babel 6.  Please either upgrade to babel 7 (what I recommend) or downgrade to babel-plugin-istanbul@4.

**Comment by coreyfarrell** [comment]
I'm submitting a fix to give a more explicit error message, babel 6 has never been supported by babel-plugin-istanbul@5, the fact that it ever worked was a bug.  #207 will add a clear error message for the next release if an attempt is made to run with babel 6.

**Comment by EricTiger** [comment]
it works. Thanks
