### ISSUE TITLE
Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by auridevil** [istanbuljs/babel-plugin-istanbul#99]
After the update of istanbul-lib-instrument it's impossible to run tests.

**Comment by bcoe** [comment]
@auridevil could you link the the repository that is having issues?

I recommend, for starters, `rm -rf ./node_modules/.cache`, it may be that there's a cache of old instrumentation in the cache folder.

**Comment by auridevil** [comment]
https://github.com/istanbuljs-archived-repos/istanbul-lib-instrument is the updated plugin.

the test that are failing are on private repos, so I can't link. 

I also removed all node_modules and npm installed new, but nothing changed.
Now I fixed disabling instanbul in .babelrc but we are loosing coverage info.

A more detailed stacktrace is:

`/Users/mox/xxxx/node_modules/babel-core/lib/transformation/file/index.js:590
      throw err;
      ^

TypeError: /Users/mox/xxxx/src/api/entity/Task/get.js: Cannot read property 'start' of undefined
    at SourceCoverage.newFunction (/Users/mox/xxxx/node_modules/istanbul-lib-instrument/dist/source-coverage.js:78:26)
    at VisitState.insertFunctionCounter (/Users/mox/xxxx/node_modules/istanbul-lib-instrument/dist/visitor.js:246:34)
    at VisitState.coverFunction (/Users/mox/xxxx/node_modules/istanbul-lib-instrument/dist/visitor.js:338:10)
    at /Users/mox/xxxx/node_modules/istanbul-lib-instrument/dist/visitor.js:314:15
    at Array.forEach (native)
    at VisitState.wrappedEntry (/Users/mox/xxxx/node_modules/istanbul-lib-instrument/dist/visitor.js:313:15)
    at NodePath._call (/Users/mox/xxxx/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/mox/xxxx/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/mox/xxxx/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/mox/xxxx/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/mox/xxxx/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/mox/xxxx/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/mox/xxxx/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/mox/xxxx/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/mox/xxxx/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/mox/xxxx/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/mox/xxxx/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/mox/xxxx/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/mox/xxxx/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/mox/xxxx/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/mox/xxxx/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/mox/xxxx/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/mox/xxxx/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/mox/xxxx/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/mox/xxxx/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/mox/xxxx/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/mox/xxxx/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/mox/xxxx/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/mox/xxxx/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/mox/xxxx/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/mox/xxxx/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/mox/xxxx/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/mox/xxxx/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/mox/xxxx/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/mox/xxxx/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/mox/xxxx/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/mox/xxxx/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/mox/xxxx/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/mox/xxxx/node_modules/babel-traverse/lib/path/context.js:115:19)
`

but the project file on top of the stacktrace change almost for every developer, so is not related to the code itself

**Comment by georeith** [comment]
```
/Users/george/Documents/marvel/canvas/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/index.js:590
      throw err;
      ^

TypeError: /Users/george/Documents/marvel/canvas/src/js/core/taskManager.js: Cannot read property 'start' of undefined
    at SourceCoverage.newFunction (/Users/george/Documents/marvel/canvas/node_modules/istanbul-lib-instrument/dist/source-coverage.js:78:26)
```

**Comment by georeith** [comment]
@auridevil Do you use `babel-plugin-rewire`?

**Comment by auridevil** [comment]
yes, also, but I found the dependency that updated the instanbul-lib-instrument was babel-plugin-instanbul

**Comment by georeith** [comment]
@auridevil Yeah it's just even after rolling it back (with full deletion of node_modules) it still errors. I think its a compatibility issue between the two. I've seen similar errors with the HTML reporter before but it didn't cause a hard fail.

**Comment by auridevil** [comment]
no, I can't roll back because the problem is caused by a dependency of a dependency that don't use the fixed version in package.json

**Comment by bcoe** [comment]
@georeith could you provide an example project bumping into this issue, or a minimal reproduction; I'd love to fix things but don't have a ton to go on.

**Comment by bcoe** [comment]
@auridevil @georeith I think I figured out the issue, could you give this a try:

`+ babel-plugin-istanbul@4.1.1`

sorry for the inconvenience.

**Comment by georeith** [comment]
@bcoe Works for me! Thanks :)

**Comment by auridevil** [comment]
@bcoe also for me, thank you!

**Comment by afenton90** [comment]
I'm currently getting this issue with `babel-plugin-istanbul` and `babel-plugin-rewire`.
It outputs:
```
Cannot read property 'start' of undefined
TypeError: Cannot read property 'start' of undefined
    at /Users/afe10/Repositories/sp-shop-select/node_modules/nyc/node_modules/istanbul-reports/lib/html/annotator.js:50:28
```

In coverage reports for seemingly random files. Any thoughts?

**Comment by bcoe** [comment]
@afenton90 try reversing the order of that you load `rewire` and `istanbul`:

https://github.com/speedskater/babel-plugin-rewire#istanbul

If this isn't the problem, please go ahead and open a new issue, ideally linking to a repo that has this issue.

**Comment by afenton90** [comment]
@bcoe This is still an issue with the order of the of plugins set as suggested.
I am seeing very strange behaviour, as the error happens on random files in each test run.
Could it be related to the issue you have raised here https://github.com/speedskater/babel-plugin-rewire/issues/187 . It seems to be the same kind of strange behaviour I am seeing.
New issue? or are you happy to track through the issue in `babel-plugin-rewire`?

**Comment by mengdage** [comment]
For those who may encounter the same problem and changing order doesn't help, I solved my bug by accident which moving other plugins out of "env". Hope it can help.

```
{
  "plugins": ["transform-object-rest-spread", "transform-runtime"],
  "env": {
    "test": {
      "plugins": ["istanbul", "rewire"]
    }
  }
}

```
